"""Drive git-cliff with a generated config that renders standard-version's CHANGELOG shape:

    ## 1.2.0 (2026-09-25)

    ### ⚠ BREAKING CHANGES

    * **api:** drop the v1 endpoints

    ### Features

    * **cli:** add --json ([#42](https://github.com/o/r/issues/42)) ([abc1234](https://github.com/o/r/commit/abc1234...))

The PR number comes from squash-merging: GitHub appends " (#N)" to the PR title, the title
becomes the commit subject, and a preprocessor turns it into a link. A project with its own
cliff.toml sets `cliff-config` and this module passes it through untouched.
"""

from __future__ import annotations

import json
import re
import shutil
import subprocess
import sys
import tempfile
from collections.abc import Iterator
from contextlib import contextmanager
from pathlib import Path

from conventional_release import git
from conventional_release.config import Config

HEADER = """\
# Changelog

All notable changes to this project will be documented in this file. Generated by
[conventional-release](https://github.com/MdaaaaO/conventional-release) from
[Conventional Commits](https://www.conventionalcommits.org).

"""


class CliffError(Exception):
    pass


def _q(value: str) -> str:
    """A TOML basic string. JSON's escaping is a subset of TOML's."""
    return json.dumps(value, ensure_ascii=False)


# Tera template. The trailing backslashes are TOML line continuations inside the """ string —
# they are what keeps the output free of stray blank lines.
_BODY = r"""
{% if version %}\
## {{ version | trim_start_matches(pat=@@PREFIX@@) }} ({{ timestamp | date(format="%Y-%m-%d") }})
{% else %}\
## Unreleased
{% endif %}\
{% set breaking = commits | filter(attribute="breaking", value=true) %}\
{% if breaking | length > 0 %}

### ⚠ BREAKING CHANGES

{% for commit in breaking %}\
* {% if commit.scope %}**{{ commit.scope }}:** {% endif %}\
{% if commit.breaking_description %}{{ commit.breaking_description | trim }}\
{% else %}{{ commit.message | trim }}{% endif %}
{% endfor %}\
{% endif %}\
{% for group, commits in commits | group_by(attribute="group") %}

### {{ group | striptags | trim }}

{% for commit in commits %}\
* {% if commit.scope %}**{{ commit.scope }}:** {% endif %}{{ commit.message | trim }}@@LINK@@
{% endfor %}\
{% endfor %}
"""

_LINK = (
    r' ([{{ commit.id | truncate(length=7, end="") }}]'
    r"(@@URL@@/commit/{{ commit.id }}))"
)


def render_config(config: Config, repo_url: str | None, *, with_header: bool) -> str:
    body = _BODY.replace("@@PREFIX@@", _q(config.tag_prefix))
    body = body.replace("@@LINK@@", _LINK.replace("@@URL@@", repo_url) if repo_url else "")

    parsers = ['  { message = "^chore\\\\(release\\\\)", skip = true },']
    for n, t in enumerate(config.types):
        pattern = _q(rf"^{re.escape(t.type)}(\(.*\))?!?:")
        if t.hidden:
            parsers.append(f"  {{ message = {pattern}, skip = true }},")
        else:
            group = _q(f"<!-- {n:02d} -->{t.section}")
            parsers.append(f"  {{ message = {pattern}, group = {group} }},")

    preprocessors = []
    if repo_url:
        # (?m): a squash commit's message is the subject *plus* the PR body, so "$" must mean
        # end of line — without the flag nothing matches.
        pattern = _q(r"(?m)\s\(#([0-9]+)\)$")
        replace = _q(" ([#${1}](" + repo_url + "/issues/${1}))")
        preprocessors.append(f"  {{ pattern = {pattern}, replace = {replace} }},")

    header = HEADER if with_header else ""
    return f'''\
[changelog]
header = {_q(header)}
body = """{body}"""
trim = true
footer = ""

[git]
conventional_commits = true
filter_unconventional = true
split_commits = false
protect_breaking_commits = true
sort_commits = "oldest"
tag_pattern = {_q("^" + re.escape(config.tag_prefix) + "[0-9]")}
commit_preprocessors = [
{chr(10).join(preprocessors)}
]
commit_parsers = [
{chr(10).join(parsers)}
]

[bump]
features_always_bump_minor = true
breaking_always_bump_major = true
initial_tag = {_q(config.tag(config.initial_version))}
'''


def binary() -> str:
    """git-cliff from this interpreter's environment (the `git-cliff` wheel), else PATH."""
    sibling = Path(sys.executable).parent / "git-cliff"
    if sibling.is_file():
        return str(sibling)
    found = shutil.which("git-cliff")
    if found is None:
        raise CliffError("git-cliff not found — install the git-cliff package")
    return found


def repo_url(config: Config) -> str | None:
    if config.repo_url:
        return config.repo_url.rstrip("/")
    remote = git.remote_url(config.root)
    return git.web_url(remote) if remote else None


@contextmanager
def _config_file(config: Config, *, with_header: bool) -> Iterator[Path]:
    if config.cliff_config:
        yield config.root / config.cliff_config
        return
    with tempfile.TemporaryDirectory(prefix="conventional-release-") as tmp:
        path = Path(tmp) / "cliff.toml"
        path.write_text(render_config(config, repo_url(config), with_header=with_header))
        yield path


def run(config: Config, *args: str, with_header: bool = False) -> str:
    with _config_file(config, with_header=with_header) as cfg:
        proc = subprocess.run(
            [binary(), "--config", str(cfg), *args],
            cwd=config.root,
            capture_output=True,
            text=True,
        )
    if proc.returncode != 0:
        raise CliffError(f"git-cliff {' '.join(args)} failed:\n{proc.stderr.strip()}")
    return proc.stdout


def bumped_version(config: Config) -> str:
    out = run(config, "--bumped-version").strip()
    return out.removeprefix(config.tag_prefix)


def unreleased_section(config: Config, version: str) -> str:
    """The section the next release will add, heading included, no header."""
    return run(config, "--unreleased", "--tag", config.tag(version), "--strip", "all").strip()


def regenerate(config: Config, version: str) -> None:
    run(
        config,
        "--tag",
        config.tag(version),
        "--output",
        str(config.changelog_path),
        with_header=True,
    )
